import { describe, it, expect, beforeEach } from "vitest";
import { Hono } from "hono";
import { eq } from "drizzle-orm";
import type { Db } from "@provara/db";
import { modelScores, abTests, abTestVariants } from "@provara/db";
import { makeTestDb } from "./_setup/db.js";
import { createAdaptiveAdminRoutes } from "../src/routes/adaptive-admin.js";
import type { ProviderRegistry, Provider } from "../src/providers/index.js";
import { POOL_KEY } from "../src/routing/adaptive/score-store.js";

const MIN_SAMPLES = parseInt(process.env.PROVARA_MIN_SAMPLES || "5", 10);

function makeProvider(name: string, models: string[]): Provider {
  return {
    name,
    models,
    complete: async () => {
      throw new Error("not used in tests");
    },
    stream: async function* () {
      throw new Error("not used in tests");
    },
  };
}

function makeRegistry(providers: Provider[]): ProviderRegistry {
  return {
    list: () => providers,
    get: (n) => providers.find((p) => p.name === n),
    getForModel: (m) => providers.find((p) => p.models.includes(m)),
    reload: () => {},
    refreshModels: async () => [],
    addCustom: () => {},
    removeCustom: () => {},
  };
}

function buildApp(db: Db, registry: ProviderRegistry) {
  const app = new Hono();
  app.route("/v1/admin/adaptive", createAdaptiveAdminRoutes(db, () => registry));
  return app;
}

async function seedScore(
  db: Db,
  taskType: string,
  complexity: string,
  provider: string,
  model: string,
  qualityScore: number,
  sampleCount = MIN_SAMPLES,
) {
  await db
    .insert(modelScores)
    .values({
      tenantId: POOL_KEY,
      taskType,
      complexity,
      provider,
      model,
      qualityScore,
      sampleCount,
      updatedAt: new Date(),
    })
    .run();
}

describe("GET /v1/admin/adaptive/low-score-cells", () => {
  let db: Db;
  beforeEach(async () => {
    db = await makeTestDb();
  });

  it("returns flagged cells sorted worst-first", async () => {
    await seedScore(db, "summarization", "simple", "openai", "gpt-4.1-nano", 1.8);
    await seedScore(db, "vision", "complex", "openai", "gpt-4.1-mini", 1.5);
    await seedScore(db, "qa", "simple", "openai", "gpt-4o", 4.5); // healthy

    const registry = makeRegistry([makeProvider("openai", ["gpt-4o", "gpt-4.1-nano", "gpt-4.1-mini"])]);
    const app = buildApp(db, registry);
    const res = await app.request("/v1/admin/adaptive/low-score-cells");
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body.cells).toHaveLength(2);
    expect(body.cells[0].taskType).toBe("vision");
    expect(body.cells[1].taskType).toBe("summarization");
  });

  it("returns an empty list when no cells are low", async () => {
    await seedScore(db, "qa", "simple", "openai", "gpt-4o", 4.5);
    const registry = makeRegistry([makeProvider("openai", ["gpt-4o"])]);
    const app = buildApp(db, registry);
    const res = await app.request("/v1/admin/adaptive/low-score-cells");
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body.cells).toEqual([]);
  });
});

describe("POST /v1/admin/adaptive/spawn-challenger", () => {
  let db: Db;
  beforeEach(async () => {
    db = await makeTestDb();
  });

  it("creates a 50/50 A/B test against a different-family challenger", async () => {
    await seedScore(db, "summarization", "simple", "openai", "gpt-4.1-nano", 1.8);
    const registry = makeRegistry([
      makeProvider("openai", ["gpt-4.1-nano"]),
      makeProvider("anthropic", ["claude-haiku-4-5-20251001"]),
    ]);
    const app = buildApp(db, registry);

    const res = await app.request("/v1/admin/adaptive/spawn-challenger", {
      method: "POST",
      body: JSON.stringify({ taskType: "summarization", complexity: "simple" }),
      headers: { "content-type": "application/json" },
    });
    expect(res.status).toBe(201);
    const body = await res.json();
    expect(body.test.testId).toBeDefined();
    expect(body.test.incumbent.model).toBe("gpt-4.1-nano");
    expect(body.test.challenger.provider).toBe("anthropic");

    const variants = await db
      .select()
      .from(abTestVariants)
      .where(eq(abTestVariants.abTestId, body.test.testId))
      .all();
    expect(variants).toHaveLength(2);
    expect(variants.every((v) => v.weight === 0.5)).toBe(true);

    const test = await db.select().from(abTests).where(eq(abTests.id, body.test.testId)).get();
    expect(test!.autoGenerated).toBe(false);
    expect(test!.status).toBe("active");
  });

  it("rejects requests for cells that are not flagged low (409 stale_state)", async () => {
    await seedScore(db, "qa", "simple", "openai", "gpt-4o", 4.5);
    const registry = makeRegistry([makeProvider("openai", ["gpt-4o", "gpt-4.1-nano"])]);
    const app = buildApp(db, registry);

    const res = await app.request("/v1/admin/adaptive/spawn-challenger", {
      method: "POST",
      body: JSON.stringify({ taskType: "qa", complexity: "simple" }),
      headers: { "content-type": "application/json" },
    });
    expect(res.status).toBe(409);
    const body = await res.json();
    expect(body.error.type).toBe("stale_state");
  });

  it("rejects when no eligible challenger exists (409 no_challenger)", async () => {
    await seedScore(db, "summarization", "simple", "openai", "gpt-4.1-nano", 1.8);
    // Only one model registered — no challenger possible.
    const registry = makeRegistry([makeProvider("openai", ["gpt-4.1-nano"])]);
    const app = buildApp(db, registry);

    const res = await app.request("/v1/admin/adaptive/spawn-challenger", {
      method: "POST",
      body: JSON.stringify({ taskType: "summarization", complexity: "simple" }),
      headers: { "content-type": "application/json" },
    });
    expect(res.status).toBe(409);
    const body = await res.json();
    expect(body.error.type).toBe("no_challenger");
  });

  it("rejects body without taskType/complexity (400)", async () => {
    const registry = makeRegistry([makeProvider("openai", ["gpt-4o"])]);
    const app = buildApp(db, registry);
    const res = await app.request("/v1/admin/adaptive/spawn-challenger", {
      method: "POST",
      body: JSON.stringify({ taskType: "qa" }),
      headers: { "content-type": "application/json" },
    });
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error.type).toBe("validation_error");
  });

  it("rejects malformed JSON (400)", async () => {
    const registry = makeRegistry([makeProvider("openai", ["gpt-4o"])]);
    const app = buildApp(db, registry);
    const res = await app.request("/v1/admin/adaptive/spawn-challenger", {
      method: "POST",
      body: "not json",
      headers: { "content-type": "application/json" },
    });
    expect(res.status).toBe(400);
  });

  it("excludes already-scored models from the challenger pick", async () => {
    await seedScore(db, "summarization", "simple", "openai", "gpt-4.1-nano", 1.8);
    // Add a previously-scored google model — it should not be picked
    // even though google is a different family.
    await seedScore(db, "summarization", "simple", "google", "gemini-2.0-flash", 4.0, 2); // below MIN_SAMPLES so cell is still lonely
    const registry = makeRegistry([
      makeProvider("openai", ["gpt-4.1-nano"]),
      makeProvider("google", ["gemini-2.0-flash", "gemini-2.5-flash"]),
    ]);
    const app = buildApp(db, registry);

    const res = await app.request("/v1/admin/adaptive/spawn-challenger", {
      method: "POST",
      body: JSON.stringify({ taskType: "summarization", complexity: "simple" }),
      headers: { "content-type": "application/json" },
    });
    expect(res.status).toBe(201);
    const body = await res.json();
    expect(body.test.challenger.model).toBe("gemini-2.5-flash");
  });
});
