import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import { eq } from "drizzle-orm";
import {
  modelScores,
  abTests,
  abTestVariants,
  requests,
  feedback,
} from "@provara/db";
import { makeTestDb } from "./_setup/db.js";
import {
  EPSILON_TIE,
  AUTO_STOP_MIN_SAMPLES,
  findTieCells,
  createAutoAbTest,
  evaluateAutoStop,
  runAutoAbCycle,
  getActiveAutoAbCells,
} from "../src/routing/adaptive/auto-ab.js";
import type { Db } from "@provara/db";

const MIN_SAMPLES = parseInt(process.env.PROVARA_MIN_SAMPLES || "5");

async function seedScore(
  db: Db,
  taskType: string,
  complexity: string,
  provider: string,
  model: string,
  qualityScore: number,
  sampleCount = MIN_SAMPLES,
) {
  await db
    .insert(modelScores)
    .values({
      taskType,
      complexity,
      provider,
      model,
      qualityScore,
      sampleCount,
      updatedAt: new Date(),
    })
    .run();
}

async function seedFeedback(
  db: Db,
  abTestId: string,
  provider: string,
  model: string,
  scores: number[],
) {
  for (const score of scores) {
    const requestId = `req-${Math.random().toString(36).slice(2)}`;
    await db
      .insert(requests)
      .values({
        id: requestId,
        provider,
        model,
        prompt: "test",
        abTestId,
        createdAt: new Date(),
      })
      .run();
    await db
      .insert(feedback)
      .values({
        id: `fb-${requestId}`,
        requestId,
        score,
        source: "user",
        createdAt: new Date(),
      })
      .run();
  }
}

describe("findTieCells", () => {
  let db: Db;
  beforeEach(async () => {
    db = await makeTestDb();
  });

  it("flags cells whose top two EMAs are within epsilon", async () => {
    await seedScore(db, "coding", "complex", "openai", "a", 4.20);
    await seedScore(db, "coding", "complex", "anthropic", "b", 4.10);
    const cells = await findTieCells(db);
    expect(cells).toHaveLength(1);
    expect(cells[0].top.model).toBe("a");
    expect(cells[0].runnerUp.model).toBe("b");
  });

  it("skips cells where gap exceeds epsilon", async () => {
    await seedScore(db, "coding", "complex", "openai", "a", 4.5);
    await seedScore(db, "coding", "complex", "anthropic", "b", 3.0);
    const cells = await findTieCells(db);
    expect(cells).toHaveLength(0);
  });

  it("requires at least 2 candidates per cell", async () => {
    await seedScore(db, "coding", "complex", "openai", "solo", 4.0);
    const cells = await findTieCells(db);
    expect(cells).toHaveLength(0);
  });

  it("requires sampleCount >= MIN_SAMPLES for both contenders", async () => {
    await seedScore(db, "coding", "complex", "openai", "a", 4.0, 2);
    await seedScore(db, "coding", "complex", "anthropic", "b", 4.0, 10);
    const cells = await findTieCells(db);
    expect(cells).toHaveLength(0);
  });

  it("rejects gap strictly greater than epsilon", async () => {
    await seedScore(db, "coding", "complex", "openai", "a", 4.0);
    await seedScore(db, "coding", "complex", "anthropic", "b", 4.0 - (EPSILON_TIE + 0.05));
    const cells = await findTieCells(db);
    expect(cells).toHaveLength(0);
  });
});

describe("createAutoAbTest", () => {
  let db: Db;
  beforeEach(async () => {
    db = await makeTestDb();
  });

  const candidate = {
    taskType: "coding",
    complexity: "complex",
    top: { provider: "openai", model: "a", qualityScore: 4.2, sampleCount: 10 },
    runnerUp: { provider: "anthropic", model: "b", qualityScore: 4.1, sampleCount: 10 },
  };

  it("creates an ab_tests row with 50/50 variants", async () => {
    const created = await createAutoAbTest(db, candidate);
    expect(created).not.toBeNull();

    const test = await db.select().from(abTests).where(eq(abTests.id, created!.id)).get();
    expect(test?.autoGenerated).toBe(true);
    expect(test?.sourceTaskType).toBe("coding");
    expect(test?.sourceComplexity).toBe("complex");
    expect(test?.status).toBe("active");

    const variants = await db
      .select()
      .from(abTestVariants)
      .where(eq(abTestVariants.abTestId, created!.id))
      .all();
    expect(variants).toHaveLength(2);
    expect(variants.map((v) => v.weight).every((w) => w === 0.5)).toBe(true);
    expect(variants.map((v) => v.model).sort()).toEqual(["a", "b"]);
  });

  it("is idempotent within cooldown window — second call returns null", async () => {
    const first = await createAutoAbTest(db, candidate);
    expect(first).not.toBeNull();
    const second = await createAutoAbTest(db, candidate);
    expect(second).toBeNull();
  });

  it("allows a new auto-test after cooldown elapses", async () => {
    vi.useFakeTimers();
    try {
      const start = new Date("2026-01-01T00:00:00Z");
      vi.setSystemTime(start);
      const first = await createAutoAbTest(db, candidate);
      expect(first).not.toBeNull();

      // Advance past cooldown (default 7 days)
      vi.setSystemTime(new Date(start.getTime() + 8 * 24 * 60 * 60 * 1000));
      const second = await createAutoAbTest(db, candidate);
      expect(second).not.toBeNull();
    } finally {
      vi.useRealTimers();
    }
  });
});

describe("evaluateAutoStop", () => {
  let db: Db;
  let testId: string;

  beforeEach(async () => {
    db = await makeTestDb();
    const created = await createAutoAbTest(db, {
      taskType: "coding",
      complexity: "complex",
      top: { provider: "openai", model: "a", qualityScore: 4.2, sampleCount: 10 },
      runnerUp: { provider: "anthropic", model: "b", qualityScore: 4.1, sampleCount: 10 },
    });
    testId = created!.id;
  });

  it("remains ongoing while samples are below threshold", async () => {
    await seedFeedback(db, testId, "openai", "a", [5]);
    await seedFeedback(db, testId, "anthropic", "b", [3]);
    const result = await evaluateAutoStop(db, testId);
    expect(result.action).toBe("ongoing");
  });

  it("resolves when samples reach threshold and margin exceeds window", async () => {
    const winnerScores = Array.from({ length: AUTO_STOP_MIN_SAMPLES }, () => 5);
    const loserScores = Array.from({ length: AUTO_STOP_MIN_SAMPLES }, () => 3);
    await seedFeedback(db, testId, "openai", "a", winnerScores);
    await seedFeedback(db, testId, "anthropic", "b", loserScores);

    const result = await evaluateAutoStop(db, testId);
    expect(result.action).toBe("resolved");
    expect(result.winner).toEqual({ provider: "openai", model: "a" });

    const updated = await db.select().from(abTests).where(eq(abTests.id, testId)).get();
    expect(updated?.status).toBe("completed");
    expect(updated?.resolvedWinner).toBe("openai/a");
    expect(updated?.resolvedAt).toBeTruthy();
  });

  it("stays ongoing when margin is within the win window", async () => {
    const scoresA = Array.from({ length: AUTO_STOP_MIN_SAMPLES }, () => 4);
    const scoresB = Array.from({ length: AUTO_STOP_MIN_SAMPLES }, () => 4);
    await seedFeedback(db, testId, "openai", "a", scoresA);
    await seedFeedback(db, testId, "anthropic", "b", scoresB);

    const result = await evaluateAutoStop(db, testId);
    expect(result.action).toBe("ongoing");
  });

  it("ignores manual (non-auto) tests", async () => {
    await db
      .update(abTests)
      .set({ autoGenerated: false })
      .where(eq(abTests.id, testId))
      .run();
    const result = await evaluateAutoStop(db, testId);
    expect(result.action).toBe("ongoing");
    expect(result.reason).toBe("not an auto-test");
  });
});

describe("runAutoAbCycle + getActiveAutoAbCells", () => {
  let db: Db;
  beforeEach(async () => {
    db = await makeTestDb();
  });

  it("creates tests for tied cells and ignores non-tied cells", async () => {
    await seedScore(db, "coding", "complex", "openai", "a", 4.2);
    await seedScore(db, "coding", "complex", "anthropic", "b", 4.1);
    await seedScore(db, "creative", "medium", "openai", "c", 4.5);
    await seedScore(db, "creative", "medium", "anthropic", "d", 3.0);

    const result = await runAutoAbCycle(db);
    expect(result.created).toHaveLength(1);
    expect(result.created[0].taskType).toBe("coding");

    const active = await getActiveAutoAbCells(db);
    expect(active).toHaveLength(1);
    expect(active[0]).toMatchObject({ taskType: "coding", complexity: "complex" });
  });

  it("does not re-create a test on a subsequent cycle within cooldown", async () => {
    await seedScore(db, "coding", "complex", "openai", "a", 4.2);
    await seedScore(db, "coding", "complex", "anthropic", "b", 4.1);

    const first = await runAutoAbCycle(db);
    expect(first.created).toHaveLength(1);

    const second = await runAutoAbCycle(db);
    expect(second.created).toHaveLength(0);
  });

  it("omits resolved tests from active cells", async () => {
    await seedScore(db, "coding", "complex", "openai", "a", 4.2);
    await seedScore(db, "coding", "complex", "anthropic", "b", 4.1);
    const cycle = await runAutoAbCycle(db);
    const testId = cycle.created[0].id;

    // force resolution manually
    await db
      .update(abTests)
      .set({ status: "completed", resolvedWinner: "openai/a", resolvedAt: new Date() })
      .where(eq(abTests.id, testId))
      .run();

    const active = await getActiveAutoAbCells(db);
    expect(active).toHaveLength(0);
  });
});
