import type { Db } from "@provara/db";
import { abTests, abTestVariants, modelScores, requests, feedback } from "@provara/db";
import { eq, and, sql, ne } from "drizzle-orm";
import { nanoid } from "nanoid";
import { MIN_SAMPLES } from "./scoring.js";

function numEnv(v: string | undefined, fallback: number): number {
  if (v === undefined || v === "") return fallback;
  const parsed = parseFloat(v);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function intEnv(v: string | undefined, fallback: number): number {
  if (v === undefined || v === "") return fallback;
  const parsed = parseInt(v, 10);
  return Number.isFinite(parsed) ? parsed : fallback;
}

/**
 * Two EMA scores within EPSILON_TIE are considered indistinguishable and
 * eligible to spawn an auto-experiment. 0.15 on a 1–5 scale ≈ 3% of the
 * dynamic range — tight enough that confident wins don't get contested,
 * loose enough that real ties surface quickly.
 */
export const EPSILON_TIE = numEnv(process.env.PROVARA_AUTO_AB_EPSILON, 0.15);

/** Days before the same cell can produce another auto-experiment. */
export const COOLDOWN_DAYS = intEnv(process.env.PROVARA_AUTO_AB_COOLDOWN_DAYS, 7);

/** Sample-count floor for each contender before a tie can trigger a test. */
export const AUTO_AB_MIN_SAMPLES = Math.max(MIN_SAMPLES, intEnv(process.env.PROVARA_AUTO_AB_MIN_SAMPLES, MIN_SAMPLES));

/** Samples under the experiment required before auto-stop evaluates. */
export const AUTO_STOP_MIN_SAMPLES = intEnv(process.env.PROVARA_AUTO_STOP_MIN_SAMPLES, 30);

/** Hard cap — auto-stop resolves once a variant reaches this many requests. */
export const AUTO_STOP_MAX_SAMPLES = intEnv(process.env.PROVARA_AUTO_STOP_MAX_SAMPLES, 200);

/** Winner is declared when its mean score exceeds the other's by this margin. */
export const AUTO_STOP_WIN_MARGIN = numEnv(process.env.PROVARA_AUTO_STOP_WIN_MARGIN, 0.3);

export interface TieCandidate {
  taskType: string;
  complexity: string;
  top: { provider: string; model: string; qualityScore: number; sampleCount: number };
  runnerUp: { provider: string; model: string; qualityScore: number; sampleCount: number };
}

/**
 * Scan `model_scores` for cells whose top two contenders are within
 * EPSILON_TIE. Each row in the result is a candidate for an auto-A/B
 * experiment — callers still apply cooldown and duplicate filtering.
 */
export async function findTieCells(db: Db): Promise<TieCandidate[]> {
  const rows = await db.select().from(modelScores).all();
  const byCell = new Map<string, typeof rows>();
  for (const row of rows) {
    if (row.sampleCount < AUTO_AB_MIN_SAMPLES) continue;
    const key = `${row.taskType}::${row.complexity}`;
    const existing = byCell.get(key);
    if (existing) existing.push(row);
    else byCell.set(key, [row]);
  }

  const candidates: TieCandidate[] = [];
  for (const [, cellRows] of byCell) {
    if (cellRows.length < 2) continue;
    const sorted = [...cellRows].sort((a, b) => b.qualityScore - a.qualityScore);
    const [top, runnerUp] = sorted;
    if (top.provider === runnerUp.provider && top.model === runnerUp.model) continue;
    const gap = Math.abs(top.qualityScore - runnerUp.qualityScore);
    if (gap >= EPSILON_TIE) continue;
    candidates.push({
      taskType: top.taskType,
      complexity: top.complexity,
      top: {
        provider: top.provider,
        model: top.model,
        qualityScore: top.qualityScore,
        sampleCount: top.sampleCount,
      },
      runnerUp: {
        provider: runnerUp.provider,
        model: runnerUp.model,
        qualityScore: runnerUp.qualityScore,
        sampleCount: runnerUp.sampleCount,
      },
    });
  }
  return candidates;
}

async function hasRecentAutoTest(db: Db, taskType: string, complexity: string): Promise<boolean> {
  const cutoff = new Date(Date.now() - COOLDOWN_DAYS * 24 * 60 * 60 * 1000);
  const row = await db
    .select({ id: abTests.id })
    .from(abTests)
    .where(
      and(
        eq(abTests.autoGenerated, true),
        eq(abTests.sourceTaskType, taskType),
        eq(abTests.sourceComplexity, complexity),
        sql`${abTests.createdAt} > ${Math.floor(cutoff.getTime() / 1000)}`,
      ),
    )
    .get();
  return Boolean(row);
}

export interface CreatedAutoTest {
  id: string;
  taskType: string;
  complexity: string;
  top: { provider: string; model: string };
  runnerUp: { provider: string; model: string };
}

/**
 * Idempotently create a 50/50 auto-A/B test for a tied cell. Returns null
 * when cooldown blocks the creation. Caller is responsible for picking
 * tenantId — auto-tests are currently global (tenantId=null) so they
 * reflect the overall model population; per-tenant variants are a future
 * extension that needs per-tenant cell score aggregation first.
 */
export async function createAutoAbTest(
  db: Db,
  candidate: TieCandidate,
): Promise<CreatedAutoTest | null> {
  if (await hasRecentAutoTest(db, candidate.taskType, candidate.complexity)) return null;

  const testId = nanoid();
  const gap = Math.abs(candidate.top.qualityScore - candidate.runnerUp.qualityScore).toFixed(3);
  const name = `auto: ${candidate.taskType}+${candidate.complexity} — ${candidate.top.model} vs ${candidate.runnerUp.model}`;
  const reason = `EMA gap ${gap} < epsilon ${EPSILON_TIE}`;

  await db
    .insert(abTests)
    .values({
      id: testId,
      name,
      description: `Auto-generated experiment for cell ${candidate.taskType}+${candidate.complexity}.`,
      status: "active",
      tenantId: null,
      autoGenerated: true,
      sourceTaskType: candidate.taskType,
      sourceComplexity: candidate.complexity,
      sourceReason: reason,
    })
    .run();

  for (const variant of [candidate.top, candidate.runnerUp]) {
    await db
      .insert(abTestVariants)
      .values({
        id: nanoid(),
        abTestId: testId,
        provider: variant.provider,
        model: variant.model,
        weight: 0.5,
        taskType: candidate.taskType,
        complexity: candidate.complexity,
      })
      .run();
  }

  return {
    id: testId,
    taskType: candidate.taskType,
    complexity: candidate.complexity,
    top: { provider: candidate.top.provider, model: candidate.top.model },
    runnerUp: { provider: candidate.runnerUp.provider, model: candidate.runnerUp.model },
  };
}

export interface VariantStats {
  provider: string;
  model: string;
  sampleCount: number;
  avgScore: number | null;
  feedbackCount: number;
}

async function getVariantStats(db: Db, testId: string): Promise<VariantStats[]> {
  const rows = await db
    .select({
      provider: requests.provider,
      model: requests.model,
      sampleCount: sql<number>`count(${requests.id})`,
    })
    .from(requests)
    .where(eq(requests.abTestId, testId))
    .groupBy(requests.provider, requests.model)
    .all();

  const feedbackRows = await db
    .select({
      provider: requests.provider,
      model: requests.model,
      avgScore: sql<number>`avg(${feedback.score})`,
      feedbackCount: sql<number>`count(${feedback.id})`,
    })
    .from(feedback)
    .innerJoin(requests, eq(feedback.requestId, requests.id))
    .where(eq(requests.abTestId, testId))
    .groupBy(requests.provider, requests.model)
    .all();

  const feedbackMap = new Map(
    feedbackRows.map((r) => [`${r.provider}/${r.model}`, { avg: r.avgScore, count: r.feedbackCount }]),
  );
  return rows.map((r) => {
    const fb = feedbackMap.get(`${r.provider}/${r.model}`);
    return {
      provider: r.provider,
      model: r.model,
      sampleCount: r.sampleCount,
      avgScore: fb?.avg ?? null,
      feedbackCount: fb?.count ?? 0,
    };
  });
}

export interface AutoStopResult {
  testId: string;
  action: "resolved" | "ongoing";
  winner?: { provider: string; model: string };
  reason?: string;
}

/**
 * Evaluate one auto-A/B test for resolution. Resolves when:
 *   1. Both variants have >= AUTO_STOP_MIN_SAMPLES requests AND one's
 *      mean user score exceeds the other's by AUTO_STOP_WIN_MARGIN, OR
 *   2. Any variant reaches AUTO_STOP_MAX_SAMPLES requests — we declare
 *      the higher-scoring variant the winner (or keep the top EMA from
 *      the source cell if scores are indistinguishable).
 */
export async function evaluateAutoStop(
  db: Db,
  testId: string,
): Promise<AutoStopResult> {
  const test = await db.select().from(abTests).where(eq(abTests.id, testId)).get();
  if (!test) return { testId, action: "ongoing", reason: "test not found" };
  if (!test.autoGenerated) return { testId, action: "ongoing", reason: "not an auto-test" };
  if (test.status !== "active") return { testId, action: "ongoing", reason: "not active" };

  const stats = await getVariantStats(db, testId);
  if (stats.length < 2) return { testId, action: "ongoing", reason: "insufficient variants" };

  const hasCap = stats.some((s) => s.sampleCount >= AUTO_STOP_MAX_SAMPLES);
  const bothReady = stats.every((s) => s.sampleCount >= AUTO_STOP_MIN_SAMPLES);
  if (!hasCap && !bothReady) return { testId, action: "ongoing", reason: "insufficient samples" };

  const scored = stats.filter((s) => s.avgScore !== null);
  if (scored.length < 2 && !hasCap) {
    return { testId, action: "ongoing", reason: "waiting for feedback" };
  }

  let winner: VariantStats | null = null;
  let reason = "";
  if (scored.length === 2) {
    const [a, b] = scored;
    const margin = (a.avgScore ?? 0) - (b.avgScore ?? 0);
    if (Math.abs(margin) >= AUTO_STOP_WIN_MARGIN) {
      winner = margin > 0 ? a : b;
      reason = `score gap ${Math.abs(margin).toFixed(2)} ≥ margin ${AUTO_STOP_WIN_MARGIN}`;
    } else if (hasCap) {
      winner = (a.avgScore ?? 0) >= (b.avgScore ?? 0) ? a : b;
      reason = `sample cap reached without decisive winner; picking higher mean`;
    }
  } else if (hasCap) {
    winner = scored[0] ?? stats[0];
    reason = `sample cap reached with limited feedback; defaulting to first variant`;
  }

  if (!winner) return { testId, action: "ongoing", reason: "no decisive winner yet" };

  await db
    .update(abTests)
    .set({
      status: "completed",
      resolvedWinner: `${winner.provider}/${winner.model}`,
      resolvedAt: new Date(),
      sourceReason: test.sourceReason
        ? `${test.sourceReason} | resolved: ${reason}`
        : `resolved: ${reason}`,
    })
    .where(eq(abTests.id, testId))
    .run();

  return {
    testId,
    action: "resolved",
    winner: { provider: winner.provider, model: winner.model },
    reason,
  };
}

/**
 * Full auto-A/B cycle: find tie cells, spawn experiments for new ones,
 * evaluate auto-stop on active ones. Designed to run as a single scheduler
 * tick — idempotent and safe to re-run.
 */
export async function runAutoAbCycle(db: Db): Promise<{
  created: CreatedAutoTest[];
  resolved: AutoStopResult[];
}> {
  const created: CreatedAutoTest[] = [];
  const candidates = await findTieCells(db);
  for (const candidate of candidates) {
    const result = await createAutoAbTest(db, candidate);
    if (result) {
      console.log(`[auto-ab] spawned experiment ${result.id} for ${result.taskType}+${result.complexity}`);
      created.push(result);
    }
  }

  const activeAutoTests = await db
    .select({ id: abTests.id })
    .from(abTests)
    .where(and(eq(abTests.autoGenerated, true), eq(abTests.status, "active")))
    .all();
  const resolved: AutoStopResult[] = [];
  for (const { id } of activeAutoTests) {
    const result = await evaluateAutoStop(db, id);
    if (result.action === "resolved") {
      console.log(`[auto-ab] resolved ${id}: winner ${result.winner?.provider}/${result.winner?.model}`);
      resolved.push(result);
    }
  }

  return { created, resolved };
}

/**
 * Cells currently under active auto-experiment. Used by the UI to tag the
 * matrix with "🔬 experimenting" overlays.
 */
export async function getActiveAutoAbCells(db: Db): Promise<{ taskType: string; complexity: string; testId: string }[]> {
  const rows = await db
    .select({
      id: abTests.id,
      taskType: abTests.sourceTaskType,
      complexity: abTests.sourceComplexity,
    })
    .from(abTests)
    .where(and(
      eq(abTests.autoGenerated, true),
      eq(abTests.status, "active"),
      ne(abTests.sourceTaskType, ""),
    ))
    .all();
  return rows
    .filter((r): r is { id: string; taskType: string; complexity: string } =>
      r.taskType !== null && r.complexity !== null,
    )
    .map((r) => ({ taskType: r.taskType, complexity: r.complexity, testId: r.id }));
}
